### ISSUE TITLE
zipx support

### ISSUE THREAD

**Issue by comShadowHarvy** [Unpackerr/unpackerr#507] opened 2024-12-04 10:32 UTC
i would like to suggest addind zipx support

**Comment by bakerboy448** [comment] 2024-12-04 13:55
Duplicate of https://github.com/Unpackerr/unpackerr/issues/489

**Closed by bakerboy448** 2024-12-04 13:55 UTC

**Comment by davidnewhall** [comment] 2024-12-04 16:46
I'd suggest not downloading zipx files. Nothing good has ever comer out of them. If you'd like to tell me otherwise, please re-open and provide your explanation.
