### ISSUE TITLE
ENV variables do not override default settings

### ISSUE THREAD

**Issue by thepaulz** [Unpackerr/unpackerr#468] opened 2024-07-22 15:53 UTC
I am running unpackerr with `docker-compose` and with the following configuration:

```
  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    hostname: unpackerr
    volumes:
      - /var/mnt/media:/data
      - /var/mnt/data/unpackerr/config:/config
    restart: unless-stopped
    user: pid:gid
    environment:
      - TZ=America/Vancouver
      - UN_PARALLEL=5
      - UN_LOG_FILE=/config/unpackerr.log
      - UN_SONARR_0_URL=http://sonarr:8989
      - UN_SONARR_0_API_KEY=xxxxx
      - UN_SONARR_0_PATHS_0=/data
      - UN_SONARR_0_SYNCTHING=true
      - UN_RADARR_0_URL=http://radarr:8310
      - UN_RADARR_0_API_KEY=xxxxx
      - UN_RADARR_0_PATHS_0=/data
      - UN_RADARR_0_SYNCTHING=true
    networks:
      - network
```

When starting the container, the following log lines are displayed:

```
[INFO] 2024/07/22 08:45:57 Unpackerr v0.14.0-716 Starting! PID: 1, UID: 1000, GID: 1000, Umask: 18, Now: 2024-07-22 08:45:58 -0700 PDT
[INFO] 2024/07/22 08:45:57 ==> GoLift Discord: https://golift.io/discord <==
[INFO] 2024/07/22 08:45:57 ==> Startup Settings <==
[INFO] 2024/07/22 08:45:57  => Using Config File: /config/unpackerr.conf, age: 3 days 20 hours 17 mins
[INFO] 2024/07/22 08:45:57  => Sonarr Config: 1 server: http://sonarr:8989, apikey:true, timeout:10s, verify ssl:false, protos:torrent, syncthing: false, delete_orig: false, delete_delay: 5m0s, paths:["/downloads"]
[INFO] 2024/07/22 08:45:57  => Radarr Config: 1 server: http://radarr:8310, apikey:true, timeout:10s, verify ssl:false, protos:torrent, syncthing: false, delete_orig: false, delete_delay: 5m0s, paths:["/downloads"]
[INFO] 2024/07/22 08:45:57  => Lidarr Config: 0 servers
[INFO] 2024/07/22 08:45:57  => Readarr Config: 0 servers
[INFO] 2024/07/22 08:45:57  => Folder Config: 0 paths, event buffer: 20000
[INFO] 2024/07/22 08:45:57  => Parallel: 5
[INFO] 2024/07/22 08:45:57  => Passwords: 0 (rar/7z)
[INFO] 2024/07/22 08:45:57  => Interval: 2m
[INFO] 2024/07/22 08:45:57  => Start/Delete Delay: 1m/5m
[INFO] 2024/07/22 08:45:57  => Retry Delay: 5m, max: 3
[INFO] 2024/07/22 08:45:57  => GUI / StdErr: false / false
[INFO] 2024/07/22 08:45:57  => Debug / Quiet: false / false
[INFO] 2024/07/22 08:45:57  => Activity / Queues: false / 1m
[INFO] 2024/07/22 08:45:57  => Directory & File Modes: 0755 & 0644
[INFO] 2024/07/22 08:45:57  => Log File: /config/unpackerr.log (10 @ 10Mb)
[INFO] 2024/07/22 08:45:57  => Webhook Configs: 0 URLs
[INFO] 2024/07/22 08:45:57  => Command Hook Configs: 0 commands
[INFO] 2024/07/22 08:45:57  => Webserver Disabled
[INFO] 2024/07/22 08:45:57 [Sonarr] Updated (http://sonarr:8989): 0 Items Queued, 0 Retrieved
[INFO] 2024/07/22 08:46:02 [Radarr] Updated (http://radarr:8310): 0 Items Queued, 0 Retrieved
```

Based on the log, it does not appear the docker environment variables are overwriting the default configuration. While `/config/unpackerr.conf` exists, the file has not been edited and contains only the default commented-out settings. 

Wondering if anyone knows what the cause is. Unpackerr appears to work correctly even though the reported path for both sonarr and radarr are wrong.

**Comment by davidnewhall** [comment] 2024-07-22 16:41
I'm not able to reproduce this. How are you starting the container?

**Comment by thepaulz** [comment] 2024-07-22 17:01
Strange. I am starting the container with `docker-compose up -d`

**Comment by davidnewhall** [comment] 2024-07-22 17:03
I just copied your compose to a fresh file, edited the volumes, user and paths. Started it, and it wrote a new default config file to /config. The env variables were used. Restart it and they're still used. Try moving to a fresh folder/file and see if it works.

**Comment by davidnewhall** [comment] 2024-07-27 18:16
Were you able to figure this out?

**Comment by davidnewhall** [comment] 2024-07-30 19:38
Let me know if you figure out how to reproduce this.

**Closed by davidnewhall** 2024-07-30 19:38 UTC

**Comment by joestump** [comment] 2025-05-06 07:40
@davidnewhall I think I might be running into this as well. I have `UN_FOLDER_0_PATH` set to `/downloads` and am seeing the following in the logs:

```
[INFO] 2025/05/06 00:39:07 [Sonarr] Completed item still waiting: XXXXXXXXXXXXXXXXXXX, no extractable files found at: /config/Downloads/complete/XXXXXXXXXXXXXXXXXXX/ (stat err: stat /config/Downloads/complete/XXXXXXXXXXXXXXXXXXX/: no such file or directory)
```

Will follow up with more details as I continue to debug.

**Comment by davidnewhall** [comment] 2025-05-06 07:41
Folder settings and Sonarr settings don't work together. Stop by Discord if you need help troubleshooting.

**Comment by joestump** [comment] 2025-05-06 08:14
For those finding this thread via Google, please note that you're probably wanting to set `UN_SONARR_0_PATHS_0` and similar for the Starr apps. I was using `UN_FOLDER_0_PATH`, which is separate functionality than the paths variables for each specific app. The super quick fix for me was to just bind mount my download folders to `/config/Downloads`. @davidnewhall I'll follow up with some proposed doc updates when I get a minute.

**Comment by davidnewhall** [comment] 2025-05-06 17:01
For this, the correct solution is to set the bind volume mount correctly. The UN_SONARR_0_PATH (and other Starr app PATH) variables should generally not be used in a Docker container.  Those are for users that cannot "just change their paths" like a Docker user can.
